/*INSERTS NA TABELA = USUARIOS ----------------------------------------------------------------------*/
INSERT INTO Usuarios VALUES (1, 'Joao Scaleao', '464.075.208-35', 'JoaoScaleao.jpeg');
INSERT INTO Usuarios VALUES (2, 'Ana', '464.075.208-35', 'a.jpeg');
INSERT INTO Usuarios VALUES (3, 'Bianca', '564.075.208-55', 'b.jpeg');
INSERT INTO Usuarios VALUES (4, 'Caroline', '664.075.258-35', 'c.jpeg');
INSERT INTO Usuarios VALUES (5, 'Daniela', '764.075.208-35', 'd.jpeg');
INSERT INTO Usuarios VALUES (6, 'Elaine', '864.075.208-75', 'e.jpeg');
INSERT INTO Usuarios VALUES (7, 'Fabiana', '404.995.208-35', 'f.jpeg');
INSERT INTO Usuarios VALUES (8, 'Giovana', '999.075.208-35', 'g.jpeg');
INSERT INTO Usuarios VALUES (9, 'Heloisa', '555.075.208-39', 'h.jpeg');
INSERT INTO Usuarios VALUES (10, 'Ingrid', '111.075.208-35', 'i.jpeg');
INSERT INTO Usuarios VALUES (11, 'Julia', '222.075.208-36', 'j.jpeg');
INSERT INTO Usuarios VALUES (12, 'Kawine', '666.075.208-35', 'k.jpeg');
INSERT INTO Usuarios VALUES (13, 'Laura', '444.075.208-45', 'l.jpeg');
INSERT INTO Usuarios VALUES (14, 'Nadila', '000.075.208-35', 'n.jpeg');
INSERT INTO Usuarios VALUES (15, 'Mayara', '888.111.208-35', 'm.jpeg');
INSERT INTO Usuarios VALUES (16, 'Orora', '777.888.208-35', 'o.jpeg');
INSERT INTO Usuarios VALUES (17, 'Rosana', '123.075.444-35', 'r.jpeg');
INSERT INTO Usuarios VALUES (18, 'Quenia', '321.075.208-99', 'q.jpeg');
INSERT INTO Usuarios VALUES (19, 'Paula', '654.075.208-12', 'p.jpeg');
INSERT INTO Usuarios VALUES (20, 'Sabrina', '789.075.208-35', 's.jpeg');
INSERT INTO Usuarios VALUES (21, 'Thaina', '147.075.208-00', 't.jpeg');
INSERT INTO Usuarios VALUES (22, 'Lorena', '369.075.208-58', 'lll.jpeg');

/*INSERTS NA TABELA = PERFIL ------------------------------------------------------------------------*/
INSERT INTO Perfil VALUES (1, 1, 'Azarias de Viera de Rezende', '1101', 'Bandeirantes', '86360-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (2, 2, 'Barbosa alves', '101', 'Bandeirantes', '12345-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (3, 3, 'Almeira da Silva', '1', 'Bandeirantes', '23456-000', 'engenheira civil', 'xxxxxxx');
INSERT INTO Perfil VALUES (4, 4, 'Azarias de Viera de Rezende', '777', 'Bandeirantes', '86360-000', 'Enfermeira', 'xxxxxxx');
INSERT INTO Perfil VALUES (5, 5, 'Comendador Luiz Meneghel', '1101', 'Bandeirantes', '99999-000', 'testemunha de Jeova', 'xxxxxxx');
INSERT INTO Perfil VALUES (6, 6, 'Rua Rio de Janeiro', '1901', 'Andira', '88880-000', 'crente', 'xxxxxxx');
INSERT INTO Perfil VALUES (7, 7, 'Rua Sao Paulo', '881', 'Andira', '16160-000', 'Enfermeira', 'xxxxxxx');
INSERT INTO Perfil VALUES (8, 8, 'Rua Santa Catarina', '5551', 'Cornelio Procopio', '88446-000', 'Motorista', 'xxxxxxx');
INSERT INTO Perfil VALUES (9, 9, 'Azarias de Viera de Rezende', '11', 'Bandeirantes', '86360-000', 'Motorista', 'xxxxxxx');
INSERT INTO Perfil VALUES (10, 10, 'Rua Mato Grosso', '222', 'Bandeirantes', '86360-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (11, 11, 'Rua Nossa Senhora da Aparecida', '9991', 'Bandeirantes', '86360-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (12, 12, 'Rua da dores', '1155', 'Bandeirantes', '86360-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (13, 13, 'Rua Nao sei mais inventa nome de rua', '7771', 'Bandeirantes', '86360-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (14, 14, 'Avenida Sao Paulo', '1551', 'Bandeirantes', '86360-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (15, 15, 'Rua Jose Ferreira de Menezes', '7071', 'Bandeirantes', '86360-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (16, 16, 'Avenida Dr Durnal de Menezes', '501', 'Londrina', '86360-000', 'estudante', 'xxxxxxx');
INSERT INTO Perfil VALUES (17, 17, 'Rua Piracicaba', '331', 'Londrina', '86360-000', 'Psicologa', 'xxxxxxx');
INSERT INTO Perfil VALUES (18, 18, 'Avenida Saudade', '4401', 'Marilia', '86360-000', 'Psicologa', 'xxxxxxx');
INSERT INTO Perfil VALUES (19, 19, 'Rua Goias', '6101', 'Marilia', '86360-000', 'Astronauta', 'xxxxxxx');
INSERT INTO Perfil VALUES (20, 20, 'Rua Minas Gerais', '77701', 'Bauru', '86360-000', 'Astronauta', 'xxxxxxx');
INSERT INTO Perfil VALUES (21, 21, 'Rua Esta quase acabando', '881', 'Bauru', '86360-000', 'Farmaceutica', 'xxxxxxx');
INSERT INTO Perfil VALUES (22, 22, 'Rua Só mais dois', '2201', 'Ourinhos', '86360-000', 'Farmaceutica', 'xxxxxxx');

/*INSERTS NA TABELA = DOCUMENTOS --------------------------------------------------------------------*/
INSERT INTO Documentos VALUES (1, 1, 'Escritura de Residencia', 'Escritura', 'escritura-de-residencia.pdf');
INSERT INTO Documentos VALUES (2, 1, 'Certidao de Casamento', 'Certidao', 'certidao-de-casamento.pdf');
INSERT INTO Documentos VALUES (3, 1, 'Certidao de Divorcio', 'Certidao', 'certidao-de-divorcio.pdf');
INSERT INTO Documentos VALUES (4, 1, 'Contrato de Servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (5, 1, 'Acordo Judicial', 'Acordo', 'acordo.pdf');
INSERT INTO Documentos VALUES (6, 2, 'Escritura de Residencia', 'Escritura', 'escritura-de-residencia.pdf');
INSERT INTO Documentos VALUES (7, 2, 'Certidao de Casamento', 'Certidao', 'certidao-de-casamento.pdf');
INSERT INTO Documentos VALUES (8, 2, 'Certidao de Divorcio', 'Certidao', 'certidao-de-divorcio.pdf');
INSERT INTO Documentos VALUES (9, 2, 'Contrato de Servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (10, 2, 'Acordo Judicial', 'Acordo', 'acordo.pdf');
INSERT INTO Documentos VALUES (11, 2, 'Ordem de servico', 'Acordo', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (12, 2, 'Ordem judicial', 'Certidao', 'ordem-judicial.pdf');
INSERT INTO Documentos VALUES (13, 2, 'Contrato de servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (14, 2, 'Ordem de servico', 'Contrato', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (15, 2, 'Acordo Judicial', 'Acordo', 'acordo-judicial.pdf');
INSERT INTO Documentos VALUES (16, 3, 'Fianca', 'Acordo', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (17, 3, 'Fianca', 'Acordo', 'ordem-judicial.pdf');
INSERT INTO Documentos VALUES (18, 3, 'Contrato de servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (19, 3, 'Ordem de servico', 'Contrato', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (20, 3, 'Acordo Judicial', 'Acordo', 'acordo-judicial.pdf');
INSERT INTO Documentos VALUES (21, 7, 'Escritura de Residencia', 'Escritura', 'escritura-de-residencia.pdf');
INSERT INTO Documentos VALUES (22, 7, 'Certidao de Casamento', 'Certidao', 'certidao-de-casamento.pdf');
INSERT INTO Documentos VALUES (23, 7, 'Certidao de Divorcio', 'Certidao', 'certidao-de-divorcio.pdf');
INSERT INTO Documentos VALUES (24, 7, 'Contrato de Servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (25, 7, 'Acordo Judicial', 'Acordo', 'acordo.pdf');
INSERT INTO Documentos VALUES (26, 8, 'Escritura de Residencia', 'Escritura', 'escritura-de-residencia.pdf');
INSERT INTO Documentos VALUES (27, 8, 'Certidao de Casamento', 'Certidao', 'certidao-de-casamento.pdf');
INSERT INTO Documentos VALUES (28, 8, 'Certidao de Divorcio', 'Certidao', 'certidao-de-divorcio.pdf');
INSERT INTO Documentos VALUES (29, 8, 'Contrato de Servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (30, 8, 'Acordo Judicial', 'Acordo', 'acordo.pdf');
INSERT INTO Documentos VALUES (31, 8, 'Ordem de servico', 'Acordo', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (32, 9, 'Ordem judicial', 'Certidao', 'ordem-judicial.pdf');
INSERT INTO Documentos VALUES (33, 9, 'Contrato de servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (34, 9, 'Ordem de servico', 'Contrato', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (35, 9, 'Acordo Judicial', 'Acordo', 'acordo-judicial.pdf');
INSERT INTO Documentos VALUES (36, 9, 'Fianca', 'Acordo', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (37, 10, 'Fianca', 'Acordo', 'ordem-judicial.pdf');
INSERT INTO Documentos VALUES (38, 10, 'Contrato de servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (39, 10, 'Ordem de servico', 'Contrato', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (40, 10, 'Acordo Judicial', 'Acordo', 'acordo-judicial.pdf');
INSERT INTO Documentos VALUES (41, 4, 'Escritura de Residencia', 'Escritura', 'escritura-de-residencia.pdf');
INSERT INTO Documentos VALUES (42, 4, 'Certidao de Casamento', 'Certidao', 'certidao-de-casamento.pdf');
INSERT INTO Documentos VALUES (43, 4, 'Certidao de Divorcio', 'Certidao', 'certidao-de-divorcio.pdf');
INSERT INTO Documentos VALUES (44, 4, 'Contrato de Servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (45, 4, 'Acordo Judicial', 'Acordo', 'acordo.pdf');
INSERT INTO Documentos VALUES (46, 4, 'Escritura de Residencia', 'Escritura', 'escritura-de-residencia.pdf');
INSERT INTO Documentos VALUES (47, 4, 'Certidao de Casamento', 'Certidao', 'certidao-de-casamento.pdf');
INSERT INTO Documentos VALUES (48, 4, 'Certidao de Divorcio', 'Certidao', 'certidao-de-divorcio.pdf');
INSERT INTO Documentos VALUES (49, 4, 'Contrato de Servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (50, 4, 'Acordo Judicial', 'Acordo', 'acordo.pdf');
INSERT INTO Documentos VALUES (51, 5, 'Escritura de Residencia', 'Escritura', 'escritura-de-residencia.pdf');
INSERT INTO Documentos VALUES (52, 5, 'Certidao de Casamento', 'Certidao', 'certidao-de-casamento.pdf');
INSERT INTO Documentos VALUES (53, 5, 'Certidao de Divorcio', 'Certidao', 'certidao-de-divorcio.pdf');
INSERT INTO Documentos VALUES (54, 5, 'Contrato de Servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (55, 5, 'Acordo Judicial', 'Acordo', 'acordo.pdf');
INSERT INTO Documentos VALUES (56, 6, 'Escritura de Residencia', 'Escritura', 'escritura-de-residencia.pdf');
INSERT INTO Documentos VALUES (57, 6, 'Certidao de Casamento', 'Certidao', 'certidao-de-casamento.pdf');
INSERT INTO Documentos VALUES (58, 6, 'Certidao de Divorcio', 'Certidao', 'certidao-de-divorcio.pdf');
INSERT INTO Documentos VALUES (59, 6, 'Contrato de Servico', 'Contrato', 'contrato-de-servico.pdf');
INSERT INTO Documentos VALUES (60, 6, 'Acordo Judicial', 'Acordo', 'acordo.pdf');
INSERT INTO Documentos VALUES (61, 19, 'Fianca', 'Acordo', 'ordem-de-servico.pdf');
INSERT INTO Documentos VALUES (62, 19, 'Fianca', 'Acordo', 'ordem-judicial.pdf');
INSERT INTO Documentos VALUES (63, 19, 'Contrato de servico', 'Contrato', 'contrato-de-servico.pdf');

/*INSERTS NA TABELA = SOLICITACOES -----------------------------------------------------------------------*/
INSERT INTO Solicitacoes VALUES (1, '2019-10-25 10:23:54+02', 2, true, 1, 2);
INSERT INTO Solicitacoes VALUES (2, '2019-10-25 10:23:54+02', 3, true, 2, 2);
INSERT INTO Solicitacoes VALUES (3, '2019-10-25 10:23:54+02', 4, false, 1, 2);
INSERT INTO Solicitacoes VALUES (4, '2019-10-25 10:23:54+02', 5, false, 1, 2);
INSERT INTO Solicitacoes VALUES (5, '2019-10-25 10:23:54+02', 6, false, 1, 2);
INSERT INTO Solicitacoes VALUES (6, '2019-10-25 10:23:54+02', 7, false, 1, 2);
INSERT INTO Solicitacoes VALUES (7, '2019-10-25 10:23:54+02', 8, true, 1, 2);
INSERT INTO Solicitacoes VALUES (8, '2019-10-25 10:23:54+02', 1, true, 19, 62);

/*INSERTS NA TABELA = ASSINATURA ------------------------------------------------------------------------------*/
INSERT INTO Assinaturas(id_Assinatura, Usuarios_idUsuarios, Documentos_idDocumentos, Solicitacoes_idSolicitacoes, localizacao) VALUES (1, 2, 2, 1, 'Sao Paulo');
INSERT INTO Assinaturas(id_Assinatura, Usuarios_idUsuarios, Documentos_idDocumentos, Solicitacoes_idSolicitacoes, localizacao) VALUES (2, 3, 2, 2, 'Rio de Janeiro');
INSERT INTO Assinaturas(id_Assinatura, Usuarios_idUsuarios, Documentos_idDocumentos, Solicitacoes_idSolicitacoes, localizacao) VALUES (3, 8, 2, 7, 'Curitiba');
INSERT INTO Assinaturas(id_Assinatura, Usuarios_idUsuarios, Documentos_idDocumentos, Solicitacoes_idSolicitacoes, localizacao) VALUES (4, 1, 62, 8, 'Marilia');
